#!/bin/sh 

rm testrun/*

../gu -1 testdata/mSample.gff -2 testdata/iSample.gff  -l LOG -d testrun  -n

ndiff=`diff expected testrun | wc -l `
if [ $ndiff -eq '0' ] 
then
	echo 'PASSED' 
else
	echo 'FAILED: Please check the LOG and the files under testrun'
fi

