#!/bin/sh
#
#  Install
###########################################################################
#
#  Purpose:  
#
#  Usage:  Install 
#
###########################################################################

cd `dirname $0`

if [ ! -r Configuration ]
then
    echo "Cannot read Configuration file." | tee -a ${LOG}
    exit 1
fi

#
# Source the configuration file.
#
. ./Configuration

echo "Installation successful."
exit 0
